USE MYSQL;
SELECT * FROM USER;

CREATE USER IF NOT EXISTS 'USERNAME1'@'LOCALHOST' IDENTIFIED BY 'PASSWORD1';

GRANT USAGE ON crm_database_awara.* TO 'USERNAME1'@'LOCALHOST';
GRANT SELECT ON *.* TO 'USERNAME1'@'localhost';
REVOKE DELETE ON *.* FROM 'USERNAME1'@'localhost';


CREATE USER IF NOT EXISTS 'USERNAME2'@'LOCALHOST' IDENTIFIED BY 'PASSWORD2';

GRANT USAGE ON crm_database_awara.* TO 'USERNAME2'@'LOCALHOST';
GRANT SELECT  ON *.* TO 'USERNAME2'@'localhost';
GRANT INSERT, UPDATE  ON crm_database_awara.projects TO 'USERNAME2'@'localhost';
GRANT INSERT, UPDATE  ON crm_database_awara.agreements TO 'USERNAME2'@'localhost';
GRANT INSERT, UPDATE  ON crm_database_awara.activities TO 'USERNAME2'@'localhost';
REVOKE DELETE ON *.* FROM 'USERNAME2'@'LOCALHOST';